/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xmap_api_XMapEntryReader */

#ifndef _Included_com_xmap_api_XMapEntryReader
#define _Included_com_xmap_api_XMapEntryReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xmap_api_XMapEntryReader
 * Method:    openMMap
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xmap_api_XMapEntryReader_openMMap
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_xmap_api_XMapEntryReader
 * Method:    openSHM
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_xmap_api_XMapEntryReader_openSHM
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_xmap_api_XMapEntryReader
 * Method:    read
 * Signature: (ILcom/xmap/api/XMapEntry;)I
 */
JNIEXPORT jint JNICALL Java_com_xmap_api_XMapEntryReader_read
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_xmap_api_XMapEntryReader
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xmap_api_XMapEntryReader_close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
